spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: tiger
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
